return {
    { "i", "<C-h>", "<Left>", "Move left" },
    { "i", "<C-k>", "<Up>", "Move up" },
    { "i", "<C-j>", "<Down>", "Move down" },
    { "i", "<C-l>", "<Right>", "Move right" },
    { "n", "<C-h>", "<C-w>h", "Select left window" },
    { "n", "<C-k>", "<C-w>k", "Select top window" },
    { "n", "<C-j>", "<C-w>j", "Select bottom window" },
    { "n", "<C-l>", "<C-w>l", "Select right window" },
    { "n", "<Leader>hh", "<C-w><S-h>", "Swap left window" },
    { "n", "<Leader>hk", "<C-w><S-k>", "Swap top window" },
    { "n", "<Leader>hj", "<C-w><S-j>", "Swap bottom window" },
    { "n", "<Leader>hl", "<C-w><S-l>", "Swap right window" },
    { "n", "<C-Up>", ":resize -2<CR>", "Shrink window (Y)" },
    { "n", "<C-Down>", ":resize +2<CR>", "Grow window (Y)" },
    { "n", "<C-Left>", ":vertical resize -2<CR>", "Shrink window (X)" },
    { "n", "<C-Right>", ":vertical resize +2<CR>", "Grow window (X)" },
}
